### ISSUE TITLE
compiled binary pls for windows

### ISSUE THREAD

**Issue by vaguiners** [cuellius/decomp#3]
i dont have visual studio

**Comment by Sqoops** [comment]
https://www.dropbox.com/s/vbckmb0v6ascrqv/Decomp.exe?dl=0

**Comment by cuellius** [comment]
I distribute binary assemblies for Windows on the Russian fan-site about M&B: http://rusmnb.ru/index.php?topic=17294.0

**Comment by cuellius** [comment]
P. S. I would distribute it on TaleWorlds, but a moderator did not allow.
